<?php
/**
 *  HTML Invoice
 *  
 *  Copyright (C) 2015 paj@gaiterjones.com 
 *
 *  v0.0.1 - 11.06.2012 - dev BETA release
 *  v0.0.2 - 15.08.2012
 	v0.13 - 26.07.2013
	v0.14.1 - 16.01.2015 - display image of parent for grouped child products
	v0.14.2 - 27.08.2015 - get date from order instead of todays date
	v0.14.3 - 02.09.2015 - display invoice/order correctly, removed notes text, added notes hide checkbox
 
 *	This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  @category   PAJ
 *  @package    HTMLInvoice
 *  @license    http://www.gnu.org/licenses/ GNU General Public License
 * 
 *
 */
	$_order = $this->getOrder();
	$_orderStoreID=$_order->getStoreId();	
	
	$_logoURL=trim(Mage::getStoreConfig('htmlinvoice_section1/general/logourl',(int)$_orderStoreID));
	$_watermarkURL=trim(Mage::getStoreConfig('htmlinvoice_section1/general/watermark',(int)$_orderStoreID));
	$_headerText=trim(Mage::getStoreConfig('htmlinvoice_section1/general/headertext',(int)$_orderStoreID));
	$_showComments=trim(Mage::getStoreConfig('htmlinvoice_section1/general/showcomments',(int)$_orderStoreID));
	$_showImages=trim(Mage::getStoreConfig('htmlinvoice_section1/general/showimages',(int)$_orderStoreID));
	$_footerText=trim(Mage::getStoreConfig('htmlinvoice_section1/general/footertext',(int)$_orderStoreID));
	$_addVat=trim(Mage::getStoreConfig('htmlinvoice_section1/general/addvat',(int)$_orderStoreID));
	$_vatRate=trim(Mage::getStoreConfig('htmlinvoice_section1/general/vatrate',(int)$_orderStoreID));
 
	// add tax to shipping amount
	//
	if ($_addVat && $_vatRate)
	{
		$shippingInclTax = $_order->getShippingAmount() + $_order->getShippingTaxAmount();
		$_order->setShippingAmount($shippingInclTax);
	}
	
	// check for invoice
	//
	if ($_order->hasInvoices()) {
		$_invoiceIdText="Invoice";
		foreach ($_order->getInvoiceCollection() as $_eachInvoice) {
			$_invoiceId = $_eachInvoice->getIncrementId();
		}
	} else {
			$_invoiceIdText="Order";
			$_invoiceId = $_order->getIncrementId();
	}


?>
<!DOCTYPE HTML>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!--<title><?php //echo $_invoiceIdText. " #". $_invoiceId; ?></title>-->
<style type="text/css">

BODY {
	font-family: Arial, Helvetica, sans-serif;
	margin: 0;
	padding: 0;
	font-size: 12px;
}
.wrapper {
	margin: 20px;
}
.all-invoice-wrapper{
	max-width: 1200px;
	width: 100%;
	margin: 20px auto;
}
.dataTableHeadingRow {
	background: none;
}
.dataTableHeadingContent {
	font-size: 12px;
	color: #000;
	padding: 6px;
	border-bottom: 2px solid #999;
}
.dataTableRow {
	background: none;
}
.dataTableContent {
	padding: 2px 6px;
	border-bottom: 1px solid #eee;
}

.alt TD { background: #eee; }

@media screen {
	#printFooter {
		display: none;
	}
}
@media print {
	#printFooter {
		position: fixed;
		bottom: 0;
	}
}

#footer {
	text-align: center;
	margin: 60px 0 0 0;
	color: #666;
}
#notes {
	border: 1px solid #999;
	width: 530px;
	height: 80px;
	padding: 5px;
	margin: 0 0 0 20px;
}
#notes TEXTAREA {
	border: none;
	width: 470px;
	height: 60px;
	overflow: hidden;
	margin: 5px 0 0 0;
	border: 0;
}
a.addr_link {
	color: #000;
	text-decoration: none;
}
.option-menu {
	padding: 8px;
	background: #eee;
	font-size: 10px;
}
.totals .label {
	padding: 5px 20px 5px 0;
}
.totals .total td {
	font-size: 1.3em;
	border-top: 1px solid #ccc;
}
div.watermark {
	display:block;
	position:fixed;
	z-index:100;
	width:100%;
	height:100%;
}
 div.content > *:first-child, x:-moz-any-link {
margin-top:0;
}/* ff only */
 div.watermark, x:-moz-any-link {
z-index:auto;
}/* ff only */
 div.watermark, x:-moz-any-link, x:default {
z-index:100;
}/* ff3 only */
 @media all and (min-width: 0px) {
div.watermark {
width:8.5in;
}
} /* opera only */
div.watermark div {
	position:absolute;
	left:0;
	width:99%;
}
/* watermark position */
/* horizontal */
div.left {
	text-align:left;
}
div.center {
	text-align:center;
}
div.right {
	text-align:right;
}
 body:last-child:not(:root:root) div.right div {
left:-160px;
}/* safari only */
/* vertical */
div.top div {
	top:0;
}
div.middle div {
	top:50%;
	margin-top:-210px;
}
div.bottom div {
	bottom:2px;
}
.clearfix:after {
	content: ".";
	display: block;
	height: 0;
	clear: both;
	visibility: hidden;
}
.clearfix {
	display: inline-block;
}  /* for IE/Mac */


.button {
	-moz-box-shadow:inset 0px 1px 0px 0px #fce2c1;
	-webkit-box-shadow:inset 0px 1px 0px 0px #fce2c1;
	box-shadow:inset 0px 1px 0px 0px #fce2c1;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ffc477), color-stop(1, #fb9e25) );
	background:-moz-linear-gradient( center top, #ffc477 5%, #fb9e25 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffc477', endColorstr='#fb9e25');
	background-color:#ffc477;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #eeb44f;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #cc9f52;
}.button:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fb9e25), color-stop(1, #ffc477) );
	background:-moz-linear-gradient( center top, #fb9e25 5%, #ffc477 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fb9e25', endColorstr='#ffc477');
	background-color:#fb9e25;
}.button:active {
	position:relative;
	top:1px;
}
#invoice{
	max-width: 1200px;
	margin: 0 auto;
}
.adress-lampen-wrapper{
	float: right;
	padding: 20px;
}
p.header-address{
 margin: 0;
 padding: 0;
 font-size: 15px;
 font-weight: bold;
}
p.standart-address{
 margin: 5px 0 0 0;	
}
</style>
<style media="print" type="text/css">
.wrapper {
	margin: 0;
}
.option-menu {
	display: none;
}
</style>
</head>
<body>
<div class="all-invoice-wrapper">
<div class="option-menu">
<?php if (!empty($_watermarkURL)): ?>
  <!-- Watermark Option -->
  <strong>Options:</strong> &nbsp;  
  <label>
	Display watermark graphic<input id="cbk_paid" type="checkbox" onchange="if(this.checked){document.getElementById('watermark_graphic').style.display = 'block';}else{document.getElementById('watermark_graphic').style.display = 'none';}"  />
	<?php if ($_showComments): ?>
	Hide Comments<input id="hide_comment" type="checkbox" onchange="if(!this.checked){document.getElementById('notes').style.display = 'block';}else{document.getElementById('notes').style.display = 'none';}"  />
    <?php endif; ?> 
  </label>
 <!-- END Watermark OPtion -->
<?php endif; ?> 
 <!-- Print Button -->
   <p>
	<a href="#" class="button" onclick="window.print(); return false;">Print</a> 
  </p>
 <!-- END Print Button -->  
</div>
<?php if (!empty($_watermarkURL)): ?>
<div id="watermark_graphic" class="watermark middle center" style="display: none;">
  <div><img src="<?php echo $_watermarkURL; ?>" /></div>
</div>
<?php endif; ?> 
<div id="invoice" class="wrapper" >
  <!-- MAIN -->
 <!--  <h1 style="float: right;"><?php //echo $_invoiceIdText ?></h1>-->


		<?php if (!empty($_logoURL)): ?>
		<div style="float: left; max-width: 400px; padding: 10px; margin-top: 20px;" id="brand_logo"> <img src="<?php echo $_logoURL; ?>"></div>
		<?php endif; ?> 
<div style="float: right; max-width: 300px; padding: 10px; margin-top: 20px;" id="brand_adress"> 
<p style="text-align: right; margin: 0 0 5px 0;">JERZY SIWY</p>
<p style="text-align: right; margin: 0 0 5px 0;"><strong>Ekotaschen.de</strong></p>
<p style="text-align: right; margin: 0 0 5px 0;"> Bergiusstr. 17</p>
<p style="text-align: right; margin: 0 0 5px 0;">30655 Hannover</p>
<p style="text-align: right; margin: 0 0 5px 0;">Ust-IdNr. *: DE286316066</p>
</div>
		<?php if (!empty($_headerText)): ?>	
		<div class="adress-lampen-wrapper">
			<?php echo $_headerText ?> 	
		</div>
		<?php endif; ?> 


  <!-- Header -->
  <table width="100%" border="0" cellspacing="0" cellpadding="2">
    <tr>
	 <?php if($_orderStoreID !=2):?>
      <td valign="top"><p><strong>Leistungsempfänger:</strong></p>
	  <?php else: ?>
	  <td valign="top"><p><strong>Adres klienta:</strong></p>
	  <?php endif; ?>
        <?php echo $_order->getBillingAddress()->format('html'); ?>
        <!-- <p><?php //echo '<a href="mailto:' . $_order->getCustomerEmail() . '"><u>' . $_order->getCustomerEmail() . '</u></a>'; ?></p>--> </td>
	  <?php if($_order->getBillingAddress()->format('html') != $_order->getShippingAddress()->format('html')):?>
	  	 <?php if($_orderStoreID !=2):?>
      <td valign="top"><p><strong>Versandadresse:</strong></p>
	  <?php else: ?>
	  <td valign="top"><p><strong>Adres do wysyłki:</strong></p>
	  <?php endif; ?>
        <?php echo $_order->getShippingAddress()->format('html'); ?> </td>
	  <?php else: ?>	
	  
	  <?php endif; ?>
	  </tr>
  </table>
   <?php if($_orderStoreID !=2):?>
  <div style="float: left; margin: 10px 0;"><?php echo "Pro-Forma Rechnung #: <strong>PRO_". $_invoiceId."</strong>"; ?></div>
   <div style="float: right; margin: 10px; font-weight: normal;">Ausstellungsdatum: <strong> <?php echo /*$_order->getCreatedAt(); */date("Y-m-d"); ?> </strong></div>
   <?php else: ?>
  <div style="float: left; margin: 10px 0;"><?php echo "Faktura #: <strong>". $_invoiceId; ?></div>
   <div style="float: right; margin: 10px; font-weight: normal;">Wystawiono: <strong> <?php echo /*$_order->getCreatedAt(); */date("Y-m-d"); ?> </strong></div>   
   <?php endif; ?>
  <div style="clear: both; min-height: 10px; width: 100%; margin-bottom: 30px;"></div>
  <?php if($_orderStoreID == 1): ?>
  <p style="font-weight: normal; margin: 5px 0 40px; ">Sehr geehrter Herr/Frau: <strong><?php echo $_order->getBillingAddress()->getFirstname().' '.$_order->getBillingAddress()->getLastname(); ?></strong> - für Ihren Auftrag bedanke ich mich und berechne für meine Leistungen:</p>
  <?php else: ?>
  <p style="font-weight: normal; margin: 5px 0 40px; ">Szanowny(a) Panie/Pani: <strong><?php echo $_order->getBillingAddress()->getFirstname().' '.$_order->getBillingAddress()->getLastname(); ?></strong> - dziekujemy za zakupy w naszym sklepie i przesyłamy rachunek Pro Forma do wglądu:</p>  
  <?php endif; ?>
  
  <!-- Order -->
  <table border="0" width="99%" cellspacing="0" cellpadding="0">
  <?php if($_orderStoreID == 1):?>
    <tr class="dataTableHeadingRow">
	<td class="dataTableHeadingContent">Bestelldatum</td>
      <td class="dataTableHeadingContent">Maßeinheit/Menge</td>
      <td class="dataTableHeadingContent">Produktname</td>
      <td class="dataTableHeadingContent" align="left">Image</td>
      <td class="dataTableHeadingContent" align="right">Bruttoeinzelpreis</td>
      <td class="dataTableHeadingContent" align="right">Brutto</td>
    </tr>
	<?php else: ?>
    <tr class="dataTableHeadingRow">
	<td class="dataTableHeadingContent">Data zakupu</td>
      <td class="dataTableHeadingContent">Ilość</td>
      <td class="dataTableHeadingContent">Nazwa produktu</td>
      <td class="dataTableHeadingContent" align="left">Obrazek</td>
      <td class="dataTableHeadingContent" align="right">Cena brutto za szt.</td>
      <td class="dataTableHeadingContent" align="right">Cena Brutto</td>
    </tr>	
	<?php endif; ?>
    <?php
	
	$_items = $_order->getAllItems();
	
	
	$x = 0; 
	
   	foreach($_items as $_item) {
		
		if ($_item->getParentItem()) continue;
		
		$_imageURL=false;
		$_product = Mage::getModel('catalog/product')->load($_item->getProductId());
		$_productType=$_product->getTypeId();

		try{
		  	// get image from either small image or normal image for simple product
			$_imageURL = Mage::helper('catalog/image')->init($_product, 'small_image')->resize(50);
		}
		catch(Exception $e) {
			$_imageURL=false;
		}		
		
		// check for mums and dads
		// -- get image from parent product of grouped products
		if ($_productType == 'simple')
		{
			if (Mage::getVersion() >= 1.4)
			{
				// Magento v1.42 +
				$_parentIdGrouped = Mage::getModel('catalog/product_type_grouped')->getParentIdsByChild( $_product->getId() );
				$_parentIdConfigurable = Mage::getModel('catalog/product_type_configurable')->getParentIdsByChild( $_product->getId() );							
			} else {
				// pre 1.42
				$_parentIdGrouped = $_product->loadParentProductIds()->getData('parent_product_ids');
				$_parentIdConfigurable = $_product->loadParentProductIds()->getData('parent_product_ids');
			}
		
			if (!empty($_parentIdGrouped[0])) // check for grouped product parent
			{
				$_parentProduct = Mage::getModel('catalog/product')->load($_parentIdGrouped[0]);
				$_imageURL = Mage::helper('catalog/image')->init($_parentProduct, 'small_image')->resize(50);
			}
		}

      echo '      <tr class="dataTableRow ' . ($x%2==0 ? "" : "alt") . '">' . "\n" .
	       '        <td class="dataTableContent" valign="middle" align="">' . $_order->getCreatedAt() . '</td>' . "\n" .
           '        <td class="dataTableContent" valign="middle" align="">' . number_format($_item->getQtyOrdered(), 0) . '</td>' . "\n" .
           '         <td class="dataTableContent" valign="middle">' . $_item->getSku() . '</td>' . "\n" . 
		   '		 <td class="dataTableContent" valign="middle">'. ($_showImages && $_imageURL ? '<img src="'. $_imageURL. '">  ' : '') .'';// $_item->getName();

		if ($_options = $_item->getProductOptions()) {
		
			$result = array();
		
            if (isset($_options['options'])) {
                $result = array_merge($result, $_options['options']);
            }
            if (isset($_options['additional_options'])) {
                $result = array_merge($result, $_options['additional_options']);
            }
            if (!empty($_options['attributes_info'])) {
                $result = array_merge($_options['attributes_info'], $result);
            }
			
			// loop and print
			foreach ($result as $_option) {
					echo "<br /><em>" . $_option["label"] . ":</em>&nbsp;&nbsp;" . $_option["value"];
			}
			
			$finalPrice=$_item->getPrice();
			$rowTotal=$_item->getRowTotal();
			
			// add tax to product price
			if ($_addVat && $_vatRate)
			{
				$finalPrice=round($_item->getPrice() + ($_item->getPrice() * ($_vatRate/100)),2);
				$rowTotal=round($_item->getRowTotal() + ($_item->getRowTotal() * ($_vatRate/100)),2);
				//$finalPrice=Mage::helper('tax')->getPrice($_product, $_product->getFinalPrice());
			}
			
			
			
			
			
        }
		

      echo '        </td>' . "\n" .
           '        <td class="dataTableContent" align="right" valign="middle"><b>' . $_order->formatPriceTxt($finalPrice) .  '</b></td>' . "\n" .
           '        <td class="dataTableContent" align="right" valign="middle"><b>' . $_order->formatPriceTxt($rowTotal) . '</b></td>' . "\n";
      echo '      </tr>' . "\n";
	  
	  $x++;
	  
    }
?>
    <tr>
	<!-- Totals -->
      <td align="right" colspan="8"><table border="0" cellspacing="0" cellpadding="2" class="totals">
          <tr>
		  <?php if($_orderStoreID == 1):?>
            <td align="right" class="label">Zusammen</td>
			<?php else: ?>
			<td align="right" class="label">Razem za produkty</td>
			<?php endif; ?>
            <td align="right"><strong><?php echo ($_addVat && $_vatRate ? $_order->formatPriceTxt(round($_order->getSubtotal() + ($_order->getSubtotal() * ($_vatRate/100)),2)) : $_order->formatPriceTxt($_order->getSubtotal())) ?></strong></td>
          </tr>
          <?php if ($_order->getShippingDescription()): ?>
          <tr>
            <td align="right" class="label"><?php echo $_order->getShippingDescription() ?></td>
            <td align="right"><strong><?php echo $_order->formatPriceTxt($_order->getShippingAmount()) ?></strong></td>
          </tr>
          <?php endif; ?>
          
          <?php if ($_order->getDiscountAmount() != 0): ?>
          <tr>
            <td align="right" class="label">Discount<?php echo $_order->getDiscountDescription() ?></td>
            <td align="right"><strong><?php echo $_order->formatPriceTxt($_order->getDiscountAmount()) ?></strong></td>
          </tr>
          <?php endif; ?>
          
          <?php if ($_order->getTaxAmount() > 0): ?>
          <tr>
		  <?php if($_orderStoreID !=2):?>
		  <td align="right" class="label">MwSt<?php echo ($_addVat ? ' ('. $_vatRate. '%)' : '') ?></td>
		  <?php else: ?>
		  <td align="right" class="label">VAT<?php echo ($_addVat ? ' ('. $_vatRate. '%)' : '') ?></td>		  
		  <?php endif; ?>
            <td align="right"><strong><?php echo $_order->formatPriceTxt($_order->getTaxAmount()) ?></strong></td>
          </tr>
          <?php endif; ?>
          <tr class="total">
		  <?php if($_orderStoreID == 1):?>
            <td align="right" class="label"><strong>Total</strong></td>
			<?php else: ?>
			<td align="right" class="label"><strong>Do zapłaty</strong></td>			
			<?php endif; ?>
            <td align="right"><strong><?php echo $_order->formatPriceTxt($_order->getGrandTotal()) ?></strong></td>
          </tr>
        </table></td>
    </tr>
  </table>
 <div style="margin: 30px 0;"> 
   <?php if($_orderStoreID == 1): ?>
  <p style="font-weight: normal; font-size: 16px;margin-bottom: 20px;"><strong>Zahlungsmethode: </strong></p>
  <p><?php //echo $_order->getPayment()->getMethodInstance()->getTitle();?>BITTE BEZAHLEN SIE NACHT VORKASSE AUF DAS KONTO:</p>
    <?php else: ?>
  <p style="font-weight: normal; font-size: 16px;margin-bottom: 20px;"><strong>Metoda płatności: </strong></p>
  <?php $metoda = $_order->getPayment()->getMethodInstance()->getTitle();?>
  <?php
    if($metoda == 'Banküberweisung'){
		echo '<p>Przelew bankowy</p>';
	}else{
		echo '<p>'.$_order->getPayment()->getMethodInstance()->getTitle().'</p>';
	}
  ?>
   <?php endif; ?>
  <?php if($_orderStoreID !=2): ?>
  
	  <?php if($_order->getPayment()->getMethodInstance()->getTitle() == 'Bank Transfer Payment'):?>
			<p>Jerzy Siwy</p>
			<p>BLZ: 25050180</p>
			<p>Konto: 0910166412</p>
			<p>IBAN DE17 2505 0180 0910 1664 12</p>
			<p>BIC/SWIFT SPKHDE2HXXX</p>
			<p>Bestellung #: <?php echo $_order->getIncrementId();?>	</p>
	  <?php else: ?>
	  
	  <?php endif; ?>
	  
  <?php else: ?>
 
	  <?php if($_order->getPayment()->getMethodInstance()->getTitle() == 'Banküberweisung'):?>
			<p>P.P.H.U. Hellux s.c.</p>
			<p>Kuniów 17b</p>
			<p>46-200 Kluczbork</p>
			<p>ING Bank Śląski</p>
			<p>69 1050 1171 1000 0022 0392 3400</p>
			<p>Rachunek #: <?php echo $_order->getIncrementId();?>	</p>
	  <?php else: ?>
	  
	  <?php endif; ?>

  <?php endif; ?>  	  
 </div>
  <?php if ($_showComments): ?>
  <div id="notes"> <strong>Notes:</strong><br />
    <!-- Comments -->
    <textarea id="comments_area"></textarea>
  </div>
  <?php endif; ?>  

  <?php if (!empty($_footerText)): ?>  
  <div id="footer">
    <p>
		<!-- Use for screen media footer text  -->
		<strong><?php echo $_footerText; ?></strong>
	</p>
  </div>
  <div id="printFooter">
    <p>
		<!-- Use for printed media footer text  -->
	</p> 
	</div>  
  <?php endif; ?>       
</div>
</div>  <!-- ENDS Main -->
</body>
</html>
